### ISSUE TITLE
Are you sure you want to use uint for position.x, position.y?

### ISSUE THREAD

**Issue by MartyWallace** [RoyalShield/royalshield-framework#2]
In your [`Position`](https://github.com/RoyalShield/royalshield-framework/blob/master/src/royalshield/geom/Position.as) class you're using `uint` for `x`, `y` and `z`. Not sure if this was intentional, as it removes the ability to represent a position below `0, 0, 0`.

This might be completely on purpose, was just curious :-)

**Comment by Mignari** [comment]
Currently negative coordinates does not exist. The initial coordinate is 0, 0, 0. Maybe int instead uint would be useful to create invalid coordinates like -1, -1, -1, but we need to provide non-negative values to [get a Tile](https://github.com/RoyalShield/royalshield-framework/blob/master/src/royalshield/world/WorldMap.as#L146).

**Comment by MartyWallace** [comment]
Makes perfect sense!
